// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvkLgRC2DEaf-V_o6Mi2tahlK9m0Z9B70',
    appId: '1:752972230058:web:04effe6eaf493de51ccfd3',
    messagingSenderId: '752972230058',
    projectId: 'fir-lab-677dd',
    authDomain: 'fir-lab-677dd.firebaseapp.com',
    storageBucket: 'fir-lab-677dd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs1paU2EmJVx1pdIMGFCDCjk9KOh4Wzfs',
    appId: '1:752972230058:android:554c198d8b5a44751ccfd3',
    messagingSenderId: '752972230058',
    projectId: 'fir-lab-677dd',
    storageBucket: 'fir-lab-677dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5bh6c02kFKV_qHnlFuEv3hpc83sj1Ro4',
    appId: '1:752972230058:ios:de81a7cc41b6fa011ccfd3',
    messagingSenderId: '752972230058',
    projectId: 'fir-lab-677dd',
    storageBucket: 'fir-lab-677dd.appspot.com',
    iosClientId: '752972230058-toosmj38odg272qhj0m6s7hmo6gj6n8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaselab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5bh6c02kFKV_qHnlFuEv3hpc83sj1Ro4',
    appId: '1:752972230058:ios:de81a7cc41b6fa011ccfd3',
    messagingSenderId: '752972230058',
    projectId: 'fir-lab-677dd',
    storageBucket: 'fir-lab-677dd.appspot.com',
    iosClientId: '752972230058-toosmj38odg272qhj0m6s7hmo6gj6n8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaselab',
  );
}
